### ISSUE TITLE
Is that library PHP5 compatible ?

### ISSUE THREAD

**Issue by simogeo** [ProjectCleverWeb/PHP-Color#3]
@ProjectCleverWeb : Thanks for your answer !

**Comment by simogeo** [comment]
https://github.com/ProjectCleverWeb/PHP-Color/wiki ... It is ! sorry

**Comment by ProjectCleverWeb** [comment]
No. (Not yet)

The docs and the library is not yet complete, However, it will be soon. PHP 5 compatibility is fairly easily done, it is largely just removing the scalar type-casting in function definitions.

Once the library is 100% tested and is ready for v1.0.0 release, I will make a folder called `php5` in the root of the repo and the autoloader will use files from there if PHP 7 cannot be detected.

**Comment by ProjectCleverWeb** [comment]
It should also be mentioned that the PHP 5 version of the library will not have any direct unit testing, and issues that do not effect PHP 7 will likely be ignored. However, it is unlikely that there will be any issues specific to PHP 5 because this library only needs very basic math equations to do its job.

**Comment by simogeo** [comment]
Yep, thanks !

**Comment by ProjectCleverWeb** [comment]
Additionally, would you mind telling me how you came across my library?

**Comment by simogeo** [comment]
I work with chroma.js when dealing with client side ... but right now, I need to use a server side (PHP) library. I searched on github (and over the web) but did not found any quality library except yours.

I have to admit, I'm quite surprise to see that few PHP color manipulation libraries !

**Comment by simogeo** [comment]
By the way, do you have any deadline to provide a PHP5 compatible lib ?

**Comment by ProjectCleverWeb** [comment]
Just added PHP 5.3+ support :)

It won't be updated again until 1.0 release, but I know your not the only one looking forward to using this library in PHP 5.

Cheers!

**Comment by simogeo** [comment]
Many thanks ! I'll try this soon.
